package com.word2anki.data.models

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class MessageTest {

    @Test
    fun `unique ID generated by default`() {
        val msg1 = Message(role = MessageRole.USER, content = "Hello")
        val msg2 = Message(role = MessageRole.USER, content = "Hello")
        assertNotEquals(msg1.id, msg2.id)
    }

    @Test
    fun `timestamp set to current time by default`() {
        val before = System.currentTimeMillis()
        val msg = Message(role = MessageRole.USER, content = "Test")
        val after = System.currentTimeMillis()
        assertTrue(msg.timestamp in before..after)
    }

    @Test
    fun `isError defaults to false`() {
        val msg = Message(role = MessageRole.ASSISTANT, content = "Hello")
        assertFalse(msg.isError)
    }

    @Test
    fun `isError can be set to true`() {
        val msg = Message(role = MessageRole.ASSISTANT, content = "Error: something", isError = true)
        assertTrue(msg.isError)
    }

    @Test
    fun `isError preserved through copy`() {
        val msg = Message(role = MessageRole.ASSISTANT, content = "Error", isError = true)
        val copied = msg.copy(content = "Updated error")
        assertTrue(copied.isError)
    }

    @Test
    fun `isError can be cleared through copy`() {
        val msg = Message(role = MessageRole.ASSISTANT, content = "Error", isError = true)
        val fixed = msg.copy(isError = false)
        assertFalse(fixed.isError)
    }

    @Test
    fun `isStreaming defaults to false`() {
        val msg = Message(role = MessageRole.ASSISTANT, content = "")
        assertFalse(msg.isStreaming)
    }

    @Test
    fun `cardPreview defaults to null`() {
        val msg = Message(role = MessageRole.USER, content = "Test")
        assertNull(msg.cardPreview)
    }

    @Test
    fun `cardPreview can be set`() {
        val card = CardPreview(
            word = "test",
            definition = "a definition",
            exampleSentence = "example",
            sentenceTranslation = "translation"
        )
        val msg = Message(role = MessageRole.ASSISTANT, content = "Response", cardPreview = card)
        assertNotNull(msg.cardPreview)
        assertEquals("test", msg.cardPreview?.word)
    }
}
